baseurl = "http://cursos.leg.ufpr.br/rday/"
publishDir = "docs"
canonifyURLs = "true"
title = "Rday"
theme = "vec"
languageCode = "en-us"
paginate = 10
disqusShortname = ""
googleAnalytics = ""

[menu]
  # Shown in the side menu.
  # [[menu.main]]
  #   name = "post"
  #   weight = 0
  #   url = "/post"
  [[menu.main]]
    name = "sobre"
    weight = 1
    url = "/sobre"
  [[menu.main]]
    name = "atividades"
    weight = 2
    url = "/atividades"
  [[menu.main]]
    name = "propostas"
    weight = 3
    url = "/propostas"
  [[menu.main]]
    name = "inscricao"
    weight = 4
    url = "/inscricao"
  [[menu.main]]
    name = "comissao"
    weight = 5
    url = "/comissao"

[params]
  Keywords = ""
  Description = "R Day RBRAS 2017"
  Avatar = "img/Rday-big-russo.svg"
  SelfIntro = "Evento satélite pré 63ª RBRAS"
  Email = ""

  GithubID = "leg-ufpr"
  TwitterID = "LEG_UFPR"
  FacebookID = ""
  LinkedInID = ""
  GoogleplusID = "+LEGUFPR"
